version: '1.0.{build}-{branch}'
image: Visual Studio 2019

# RDP Debugging
init:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
- ps: Get-Date
- ps: Invoke-WebRequest https://www.dropbox.com/s/0n5lzzg83bha8g5/windows-2019-standard-virtualbox.box?dl=1 -OutFile windows-2019-standard-virtualbox.box
- ps: Get-Date
- ps: ls
- Dism /online /disable-feature /featurename:Microsoft-Hyper-V /NoRestart || exit 0
- choco feature disable --name showDownloadProgress
- choco install virtualbox --version=6.1.12 --ignore-detected-reboot --ignore-package-exit-codes && exit 0
#- choco install virtualbox --version=6.0.24 --ignore-detected-reboot --ignore-package-exit-codes && exit 0
- choco install vagrant --version=2.2.9 --yes --ignore-detected-reboot --ignore-package-exit-codes && exit 0
- vagrant box add windows-2019-standard-virtualbox.box --name danielmenezesbr/WindowsServerDC
- vagrant box list
on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

cache:
#  - C:\ProgramData\chocolatey\lib -> appveyor.yml
#  - C:\Vagrant -> appveyor.yml
#  - C:\Users\appveyor\.vagrant.d -> appveyor.yml
#  - C:\Users\appveyor\.vagrant.d\boxes

install:
  - set PATH=C:\Vagrant\HashiCorp\Vagrant\bin;C:\VBox;%PATH%
  - set TEST_VAR=Hello, world!
  - echo before reboot
  - ps: Restart-Computer -Force      # here the server goes restarting
  - ps: Start-Sleep -s 10
#  - ps: mkdir C:\Users\appveyor\.vagrant.d | Out-Null
#  - dism.exe /Online /Disable-Feature:Microsoft-Hyper-V /Quiet
#  - choco install virtualbox
#  - choco install virtualbox --version=5.2.42
#  - ps: Start-FileDownload "https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_x86_64.msi"
#  - ps: Start-Process -FilePath "msiexec.exe" -ArgumentList "/a vagrant_2.2.9_x86_64.msi /qb TARGETDIR=C:\Vagrant" -Wait  
build_script:
  - echo after reboot
  - echo %TEST_VAR%
#  - ps: vagrant box add cdaf/WindowsServerDC --provider virtualbox
#  - ps: ((Get-Content -path C:\Users\appveyor\.vagrant.d\boxes\cdaf-VAGRANTSLASH-WindowsServerDC\2020.05.14\virtualbox\box.ovf -Raw) -replace '<Display controller="VBoxSVGA" VRAMSize="128"/>','') | Set-Content -Path C:\Users\appveyor\.vagrant.d\boxes\cdaf-VAGRANTSLASH-WindowsServerDC\2020.05.14\virtualbox\box.ovf
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#  - ps: |
#      $where = vagrant up 2>&1
#      if($LASTEXITCODE -ne 0){
#        vagrant halt --force
#      }
#  - ps: vagrant up
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
