version: '1.0.{build}-{branch}'
image: Visual Studio 2019

# RDP Debugging
init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
- ps: Uninstall-WindowsFeature -Name Hyper-V -IncludeManagementTools -Restart
- echo "test"

on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

cache:
#  - C:\ProgramData\chocolatey\lib -> appveyor.yml
#  - C:\Vagrant -> appveyor.yml
#  - C:\Users\appveyor\.vagrant.d -> appveyor.yml
#  - C:\Users\appveyor\.vagrant.d\boxes

install:
  - ps: Get-Date
  - ps: bcdedit /set hypervisorlaunchtype off;
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#  - ps: Restart-Computer -Force
#  - ps: Start-Sleep -s 10
#  - ps: Invoke-WebRequest https://storage.googleapis.com/vagrantvms/windows-2019-standard-virtualbox.box -OutFile windows-2019-standard-virtualbox.box
  - ps: Get-Date
  - ps: ls
#  - choco feature disable --name showDownloadProgress
#  - choco install virtualbox --version=6.1.12 --ignore-detected-reboot --ignore-package-exit-codes && exit 0
#  - choco install virtualbox --version=6.0.24 --ignore-detected-reboot --ignore-package-exit-codes && exit 0
#  - choco install vagrant --version=2.2.9 --yes --ignore-detected-reboot --ignore-package-exit-codes && exit 0
  - set PATH=C:\Vagrant\HashiCorp\Vagrant\bin;C:\VBox;%PATH%
  - set TEST_VAR=Hello
  - echo before reboot
#  - ps: Restart-Computer -Force
#  - ps: mkdir C:\Users\appveyor\.vagrant.d | Out-Null
#  - dism.exe /Online /Disable-Feature:Microsoft-Hyper-V /Quiet
#  - choco install virtualbox
#  - choco install virtualbox --version=5.2.42
#  - ps: Start-FileDownload "https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_x86_64.msi"
#  - ps: Start-Process -FilePath "msiexec.exe" -ArgumentList "/a vagrant_2.2.9_x86_64.msi /qb TARGETDIR=C:\Vagrant" -Wait

build_script:
  - echo after reboot
  - echo %TEST_VAR%
  - systeminfo
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - vagrant box add windows-2019-standard-virtualbox.box --name danielmenezesbr/WindowsServerDC
  - vagrant box list
#  - ps: vagrant box add cdaf/WindowsServerDC --provider virtualbox
#  - ps: ((Get-Content -path C:\Users\appveyor\.vagrant.d\boxes\cdaf-VAGRANTSLASH-WindowsServerDC\2020.05.14\virtualbox\box.ovf -Raw) -replace '<Display controller="VBoxSVGA" VRAMSize="128"/>','') | Set-Content -Path C:\Users\appveyor\.vagrant.d\boxes\cdaf-VAGRANTSLASH-WindowsServerDC\2020.05.14\virtualbox\box.ovf
#  - ps: |
#      $where = vagrant up 2>&1
#      if($LASTEXITCODE -ne 0){
#        vagrant halt --force
#      }
#  - ps: vagrant up
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
