version: '1.0.{build}-{branch}'
image: Visual Studio 2019

# RDP Debugging
init:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
- Dism /online /disable-feature /featurename:Microsoft-Hyper-V /NoRestart || exit 0
on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

cache:
#  - C:\ProgramData\chocolatey\lib -> appveyor.yml
#  - C:\Vagrant -> appveyor.yml
#  - C:\Users\appveyor\.vagrant.d -> appveyor.yml
#  - C:\Users\appveyor\.vagrant.d\boxes

install:
  - set TEST_VAR=Hello, world!
  - echo before reboot
  - ps: Restart-Computer -Force            # here the server goes restarting
  - echo Before sleep
  - ps: |
     Write-Host $env:TEST_VAR
     Write-Host ([datetime]::Now)
     Start-Sleep -s 10
     Write-Host "After sleep"
     Write-Host ([datetime]::Now)
#  - ps: shutdown -s -t 0
#  - ps: Restart-Computer -Force -Verbose
  - shutdown /r /t 00 /f
  - ps: systeminfo
  - ps: systeminfo
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - ps: systeminfo
#  - ps: mkdir C:\Users\appveyor\.vagrant.d | Out-Null
  - choco feature disable --name showDownloadProgress
  - choco install vagrant --version=2.2.9 --yes --ignore-detected-reboot --ignore-package-exit-codes && exit 0
#  - dism.exe /Online /Disable-Feature:Microsoft-Hyper-V /Quiet
  - choco install virtualbox
#  - choco install virtualbox --version=6.0.24
#  - choco install virtualbox --version=5.2.42
#  - ps: Start-FileDownload "https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_x86_64.msi"
#  - ps: Start-Process -FilePath "msiexec.exe" -ArgumentList "/a vagrant_2.2.9_x86_64.msi /qb TARGETDIR=C:\Vagrant" -Wait
  - set PATH=C:\Vagrant\HashiCorp\Vagrant\bin;C:\VBox;%PATH%
  # Vagrant correctly installed?
  - vagrant --version
  - ssh -V
  - ipconfig /all

build_script:
  - ps: vagrant box add cdaf/WindowsServerDC --provider virtualbox
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))  
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))  
#  - ps: ((Get-Content -path C:\Users\appveyor\.vagrant.d\boxes\cdaf-VAGRANTSLASH-WindowsServerDC\2020.05.14\virtualbox\box.ovf -Raw) -replace '<Display controller="VBoxSVGA" VRAMSize="128"/>','') | Set-Content -Path C:\Users\appveyor\.vagrant.d\boxes\cdaf-VAGRANTSLASH-WindowsServerDC\2020.05.14\virtualbox\box.ovf
  - ps: Test-NetConnection google.com -Port 80
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - ps: |
      $where = vagrant up 2>&1
      if($LASTEXITCODE -ne 0){
        vagrant halt --force
      }
  - ps: vagrant up
